const DATABASE_NAME = '@gamepley';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export {
    COLLECTION_USERS,
    COLLECTION_APPOINTMENTS
}